# This is a Docker Compose file for setting up the morphic-stack environment.

version: '3.9'
services:
  morphic:
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile
    command: bun dev # Use `bun dev -H 0.0.0.0` to listen on all interfaces
    ports:
      - ":3000" # Maps port 3000 on the host to port 3000 in the container. # Required
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      # Optional environment variables
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL:-gpt-4o-mini}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_SUB_MODEL=${OLLAMA_SUB_MODEL}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - USE_SPECIFIC_API_FOR_WRITER=${USE_SPECIFIC_API_FOR_WRITER}
      - SPECIFIC_API_BASE=${SPECIFIC_API_BASE}
      - SPECIFIC_API_KEY=${SPECIFIC_API_KEY}
      - SPECIFIC_API_MODEL=${SPECIFIC_API_MODEL}
      - ENABLE_SHARE=${ENABLE_SHARE}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - SEARXNG_IMAGE_PROXY=${SEARXNG_IMAGE_PROXY:-true}
      - SEARXNG_API_URL=${SEARXNG_API_URL:-http://searxng:8080}
      - SEARCH_API=${SEARCH_API:-tavily}
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_LIMITER=${SEARXNG_LIMITER:-false}
      - SEARXNG_DEFAULT_DEPTH=${SEARXNG_DEFAULT_DEPTH:-100}
      - SEARXNG_MAX_RESULTS=${SEARXNG_MAX_RESULTS:-100}
      - SEARXNG_CRAWL_MULTIPLIER=${SEARXNG_CRAWL_MULTIPLIER:-4}
      - SEARXNG_ENGINES=${SEARXNG_ENGINES:-google,bing,duckduckgo,wikipedia}
      - SEARXNG_TIME_RANGE=${SEARXNG_TIME_RANGE:-None}
      - SEARXNG_SAFESEARCH=${SEARXNG_SAFESEARCH:-0}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - USE_LOCAL_REDIS=${USE_LOCAL_REDIS:-false}
      - LOCAL_REDIS_URL=${LOCAL_REDIS_URL:-redis://redis:6379}
    restart: unless-stopped

volumes:
  morphic-data:
